Update cypress.yml

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -32,6 +32,12 @@ jobs:
           browser: 'chrome'
         env: 
           MATRIX_CONTAINER: ${{ matrix.container }} 
+      - name: Verify Report Files
+        run: |
+          echo "Checking directory: cypress/reports/mocha/Regression-${{ matrix.container }}/.jsons/"
+          ls -l cypress/reports/mocha/Regression
+          ls -l cypress/reports/mocha/Regression-${{ matrix.container }}/.jsons/ || echo "Directory or files not found."
+      
       # Step 4: Create Zip Archive of Mocha Reports
       - name: Zip Mocha Report Files
         if: ${{ always() }}  
